### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by znrm** [znrm/sage#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by s-pangburn** [comment]
- [ ] Update your wiki to have a live link to your website! (possibly the README too, but that's not necessary at this stage.)
- [ ] Ideally I think your buttons should highlight or darken a little on hover. Not strictly necessary, but in my opinion it makes the site more dynamic. I'll leave it up to your personal taste though 🙂 
- [ ] ~If you got those errors displaying, please push those changes to heroku! If you have not, get errors displaying!!~ I refreshed and it works now, my bad.
- [ ] Remove the "Remember Me" until it is functional.
- [ ] ~I've tried several different username/email/password combinations but for some reason your site won't let me sign up. Because your errors do not display, it isn't clear why this is. I've tried various password lengths, usernames, and emails. This prevents any further testing.~ Nevermind.
- [ ] 12 characters is too much for a minimum password length in my opinion. Just long enough to be annoying to a recruiter just poking around. (I also might just be biased because I wasn't getting errors at first and it was hard to tell you wanted 12 characters, it's actually probably fine, but I'll just leave this here as something to consider.)
- [ ] Errors should clear when switching between forms! When I click "Sign up for an account" at the bottom my errors persist.
- [ ] Your "Logout" button should `cursor: pointer` on hover.
- [ ] Once you're logged in, ideally you should be redirected to root or some other url (you will probably do this eventually anyway, but since it is part of user auth (the final part) I figured it should probably be in the requirements for it.

Overall, great job Zaniar! What's here is very polished so far 🙂 Address this feedback and I'll sign off on this MVP.

**Comment by s-pangburn** [comment]
Great work Zaniar! One final thing:

- [ ] You don't validate the presence of username or email. I just successfully signed up for your website using only a password:
![screen shot 2018-08-13 at 9 33 41 am](https://user-images.githubusercontent.com/8031316/44045126-6d9ed6ee-9edc-11e8-9412-0e4aef6fe9fc.png)
![screen shot 2018-08-13 at 9 34 36 am](https://user-images.githubusercontent.com/8031316/44045127-72d96ef8-9edc-11e8-9cd2-01c1e3ed032c.png)
  - Remove the blank user account from Heroku (`heroku run rails c`) and fix this validation, then this MVP will be considered complete!

**Comment by znrm** [comment]
I have removed the blank user, and the fixed version has been pushed to production!

**Comment by s-pangburn** [comment]
💯
